version: '3'

services:
  api:
    deploy:
      replicas: 2
    image: paulachocolat-back
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - ./mydb.sqlite:/paula-chocolat/back-end/mydb.sqlite